# This is a basic workflow to help you get started with Actions

name: Scheduled-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run script file
        run: |
          cd aks-version
          chmod +x ./miniconda.sh
          ./miniconda.sh
        shell: bash

      - name: Create conda environment
        run: |
          cd aks-version
          conda env create -f conda.yml -n aks_version
          conda init
        shell: bash

      - name: Send email
        run: |
          AZURE_CLIENT_SECRET=TXh8Q~taSEfYLFEIDCoN5bx.RBf1JI1w9xsdhbii
          AZURE_TENANT_ID=93f33571-550f-43cf-b09f-cd331338d086
          AZURE_CLIENT_ID=923f3966-5710-45e3-969b-0786a54f92e1
          cd aks-version
          conda activate aks_version

        shell: bash
